version: '3'

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app_mounted_src:rw
    ports:
      - "8000:8000"

  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9002:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio124
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  click_server:
    image: yandex/clickhouse-server
    ports:
      - "9000:9000"
    volumes:
      - ./dbfiles:/var/lib/clickhouse

  click_client:
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity

volumes:
  minio-storage:
